aegis rebrand thanks to @gemini

diff --git a/.github/workflows/ci-server.yaml b/.github/workflows/ci-server.yaml
--- a/.github/workflows/ci-server.yaml
+++ b/.github/workflows/ci-server.yaml
@@ -22,13 +22,13 @@ jobs:
       files: |
         package.json
         yarn.lock
-        packages/twenty-server/**
-        packages/twenty-front/src/generated/**
-        packages/twenty-front/src/generated-metadata/**
-        packages/twenty-front/src/generated-admin/**
-        packages/twenty-client-sdk/**
-        packages/twenty-emails/**
-        packages/twenty-shared/**
+        packages/aegis-server/**
+        packages/aegis-front/src/generated/**
+        packages/aegis-front/src/generated-metadata/**
+        packages/aegis-front/src/generated-admin/**
+        packages/aegis-client-sdk/**
+        packages/aegis-emails/**
+        packages/aegis-shared/**
 
   server-build:
     needs: changed-files-check
@@ -47,12 +47,12 @@ jobs:
         uses: ./.github/actions/restore-cache
         with:
           key: ${{ env.SERVER_BUILD_CACHE_KEY }}
-      - name: Build twenty-shared
-        run: npx nx build twenty-shared
+      - name: Build aegis-shared
+        run: npx nx build aegis-shared
       - name: Server / Write .env
-        run: npx nx reset:env twenty-server
+        run: npx nx reset:env aegis-server
       - name: Server / Build
-        run: npx nx build twenty-server
+        run: npx nx build aegis-server
       - name: Save server build cache
         uses: ./.github/actions/save-cache
         with:
@@ -70,8 +70,8 @@ jobs:
           fetch-depth: 10
       - name: Install dependencies
         uses: ./.github/actions/yarn-install
-      - name: Build twenty-shared
-        run: npx nx build twenty-shared
+      - name: Build aegis-shared
+        run: npx nx build aegis-shared
       - name: Server / Run lint & typecheck
         uses: ./.github/actions/nx-affected
         with:
@@ -110,27 +110,27 @@ jobs:
         uses: ./.github/actions/restore-cache
         with:
           key: ${{ env.SERVER_BUILD_CACHE_KEY }}
-      - name: Build twenty-shared
-        run: npx nx build twenty-shared
+      - name: Build aegis-shared
+        run: npx nx build aegis-shared
       - name: Server / Write .env
-        run: npx nx reset:env twenty-server
+        run: npx nx reset:env aegis-server
       - name: Server / Build
-        run: npx nx build twenty-server
+        run: npx nx build aegis-server
       - name: Server / Create DB
         run: |
           PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d postgres -c 'CREATE DATABASE "default";'
           PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d postgres -c 'CREATE DATABASE "test";'
-          npx nx run twenty-server:database:init:prod
+          npx nx run aegis-server:database:init:prod
       - name: Worker / Run
         run: |
-          timeout 30s npx nx run twenty-server:worker || exit_code=$?
+          timeout 30s npx nx run aegis-server:worker || exit_code=$?
           if [ $exit_code -eq 124 ]; then
             exit 0
           elif [ $exit_code -ne 0 ]; then
             exit $exit_code
           fi
       - name: Server / Start
-        run: npx nx start:ci twenty-server &
+        run: npx nx start:ci aegis-server &
       - name: Waiting for server starting...
         run: |
           for i in {1..10}; do
@@ -145,10 +145,10 @@ jobs:
           exit 1
       - name: Server / Check for Pending Migrations
         run: |
-          npx nx database:migrate:generate twenty-server -- --name pending-migration-check || true
+          npx nx database:migrate:generate aegis-server -- --name pending-migration-check || true
 
           if ! git diff --quiet; then
-            echo "::error::Unexpected migration files were generated. Please run 'npx nx database:migrate:generate twenty-server -- --name <migration-name>' and commit the result."
+            echo "::error::Unexpected migration files were generated. Please run 'npx nx database:migrate:generate aegis-server -- --name <migration-name>' and commit the result."
             echo ""
             echo "The following migration changes were detected:"
             echo "==================================================="
@@ -164,29 +164,29 @@ jobs:
         run: |
           HAS_ERRORS=false
 
-          npx nx run twenty-front:graphql:generate
-          npx nx run twenty-front:graphql:generate --configuration=metadata
-          npx nx run twenty-front:graphql:generate --configuration=admin
+          npx nx run aegis-front:graphql:generate
+          npx nx run aegis-front:graphql:generate --configuration=metadata
+          npx nx run aegis-front:graphql:generate --configuration=admin
 
-          if ! git diff --quiet -- packages/twenty-front/src/generated packages/twenty-front/src/generated-metadata packages/twenty-front/src/generated-admin; then
+          if ! git diff --quiet -- packages/aegis-front/src/generated packages/aegis-front/src/generated-metadata packages/aegis-front/src/generated-admin; then
             echo "::error::GraphQL schema changes detected. Please run the three graphql:generate configurations ('data', 'metadata', 'admin') and commit the changes."
             echo ""
             echo "The following GraphQL schema changes were detected:"
             echo "==================================================="
-            git diff -- packages/twenty-front/src/generated packages/twenty-front/src/generated-metadata packages/twenty-front/src/generated-admin
+            git diff -- packages/aegis-front/src/generated packages/aegis-front/src/generated-metadata packages/aegis-front/src/generated-admin
             echo "==================================================="
             echo ""
             HAS_ERRORS=true
           fi
 
-          npx nx run twenty-client-sdk:generate-metadata-client
+          npx nx run aegis-client-sdk:generate-metadata-client
 
-          if ! git diff --quiet -- packages/twenty-client-sdk/src/metadata/generated; then
-            echo "::error::SDK metadata client changes detected. Please run 'npx nx run twenty-client-sdk:generate-metadata-client' and commit the changes."
+          if ! git diff --quiet -- packages/aegis-client-sdk/src/metadata/generated; then
+            echo "::error::SDK metadata client changes detected. Please run 'npx nx run aegis-client-sdk:generate-metadata-client' and commit the changes."
             echo ""
             echo "The following SDK metadata client changes were detected:"
             echo "==================================================="
-            git diff -- packages/twenty-client-sdk/src/metadata/generated
+            git diff -- packages/aegis-client-sdk/src/metadata/generated
             echo "==================================================="
             echo ""
             HAS_ERRORS=true
@@ -210,8 +210,8 @@ jobs:
         uses: ./.github/actions/restore-cache
         with:
           key: ${{ env.SERVER_BUILD_CACHE_KEY }}
-      - name: Build twenty-shared
-        run: npx nx build twenty-shared
+      - name: Build aegis-shared
+        run: npx nx build aegis-shared
       - name: Server / Run Tests
         uses: ./.github/actions/nx-affected
         with:
@@ -247,7 +247,7 @@ jobs:
         image: clickhouse/clickhouse-server:25.8.8
         env:
           CLICKHOUSE_PASSWORD: clickhousePassword
-          CLICKHOUSE_URL: "http://default:clickhousePassword@localhost:8123/twenty"
+          CLICKHOUSE_URL: "http://default:clickhousePassword@localhost:8123/aegis"
         ports:
           - 8123:8123
           - 9000:9000
@@ -259,7 +259,7 @@ jobs:
     env:
       NODE_ENV: test
       ANALYTICS_ENABLED: true
-      CLICKHOUSE_URL: "http://default:clickhousePassword@localhost:8123/twenty"
+      CLICKHOUSE_URL: "http://default:clickhousePassword@localhost:8123/aegis"
       CLICKHOUSE_PASSWORD: clickhousePassword
       SHARD_COUNTER: 10
     steps:
@@ -282,18 +282,18 @@ jobs:
         with:
           key: ${{ env.SERVER_BUILD_CACHE_KEY }}
       - name: Server / Build
-        run: npx nx build twenty-server
+        run: npx nx build aegis-server
       - name: Build dependencies
         run: |
-          npx nx build twenty-shared
-          npx nx build twenty-emails
+          npx nx build aegis-shared
+          npx nx build aegis-emails
       - name: Server / Create Test DB
         run: |
           PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d postgres -c 'CREATE DATABASE "test";'
       - name: Run ClickHouse migrations
-        run: npx nx clickhouse:migrate twenty-server
+        run: npx nx clickhouse:migrate aegis-server
       - name: Run ClickHouse seeds
-        run: npx nx clickhouse:seed twenty-server
+        run: npx nx clickhouse:seed aegis-server
       - name: Server / Run Integration Tests
         uses: ./.github/actions/nx-affected
         with:
