chore: slim down project by using official @twenty-hq npm packages

diff --git a/.github/workflows/ci-server.yaml b/.github/workflows/ci-server.yaml
--- a/.github/workflows/ci-server.yaml
+++ b/.github/workflows/ci-server.yaml
@@ -26,7 +26,7 @@ jobs:
         packages/aegis-front/src/generated/**
         packages/aegis-front/src/generated-metadata/**
         packages/aegis-front/src/generated-admin/**
-        packages/aegis-client-sdk/**
+        packages/twenty-client-sdk/**
         packages/aegis-emails/**
         packages/aegis-shared/**
 
@@ -179,14 +179,14 @@ jobs:
             HAS_ERRORS=true
           fi
 
-          npx nx run aegis-client-sdk:generate-metadata-client
+          npx nx run twenty-client-sdk:generate-metadata-client
 
-          if ! git diff --quiet -- packages/aegis-client-sdk/src/metadata/generated; then
-            echo "::error::SDK metadata client changes detected. Please run 'npx nx run aegis-client-sdk:generate-metadata-client' and commit the changes."
+          if ! git diff --quiet -- packages/twenty-client-sdk/src/metadata/generated; then
+            echo "::error::SDK metadata client changes detected. Please run 'npx nx run twenty-client-sdk:generate-metadata-client' and commit the changes."
             echo ""
             echo "The following SDK metadata client changes were detected:"
             echo "==================================================="
-            git diff -- packages/aegis-client-sdk/src/metadata/generated
+            git diff -- packages/twenty-client-sdk/src/metadata/generated
             echo "==================================================="
             echo ""
             HAS_ERRORS=true
